package util

enum class DbAction {
    NONE,

    NEW_RECORD,
    REMOVE_RECORD_BY_NAME,
    REMOVE_RECORD_BY_ID,
    LIST_ALL_RECORDS,
    LIST_RECORDS_BY_FILTER,
    GET_RECORD_FROM_ID,

    AVERAGE_OF_FIELD,
    SUM_OF_FIELD,
    MAX_OF_FIELD,
    MIN_OF_FIELD,

    NEW_TABLE,
    ERASE_TABLE,
    REMOVE_TABLE,
    LIST_ALL_TABLES,
    GET_TABLE_TYPE
}